#!/usr/bin/env node

/**
 * Standalone script to regenerate HAProxy configuration
 * Run this from the daemon directory: node scripts/regenerate-haproxy.js
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const CONFIG_DIR = path.join(process.cwd(), 'haproxy');
const BACKENDS_FILE = path.join(CONFIG_DIR, 'backends.json');
const HAPROXY_CONFIG = path.join(CONFIG_DIR, 'haproxy.cfg');
const HAPROXY_SYSTEM_CONFIG = '/etc/haproxy/haproxy.cfg';

// Load backends
function loadBackends() {
  if (!fs.existsSync(BACKENDS_FILE)) {
    console.log('No backends.json found. No databases configured in HAProxy.');
    return {};
  }
  
  try {
    const data = fs.readFileSync(BACKENDS_FILE, 'utf-8');
    return JSON.parse(data);
  } catch (error) {
    console.error('Failed to load backends:', error.message);
    return {};
  }
}

// Generate HAProxy config
function generateConfig(postgresBackends, mysqlBackends) {
  let config = `# HAProxy Configuration
# Auto-generated by Grumpy Wombat Daemon
# DO NOT EDIT MANUALLY - Changes will be overwritten

global
    daemon
    maxconn 4096
    user haproxy
    group haproxy

defaults
    mode    tcp
    timeout connect 10s
    timeout client  1m
    timeout server  1m

`;

  // PostgreSQL frontend
  if (postgresBackends.length > 0) {
    config += `# PostgreSQL Databases (port 5432)\n`;
    config += `frontend postgres_frontend\n`;
    config += `    bind *:5432\n`;
    config += `    mode tcp\n`;
    config += `    tcp-request inspect-delay 5s\n`;
    config += `    tcp-request content accept if { req_ssl_hello_type 1 }\n`;

    for (const backend of postgresBackends) {
      const backendName = `postgres_${backend.instanceName.replace(/[^a-z0-9]/g, '_')}`;
      config += `    use_backend ${backendName} if { req.ssl_sni -i ${backend.domain} }\n`;
    }

    if (postgresBackends.length === 1) {
      const backend = postgresBackends[0];
      const backendName = `postgres_${backend.instanceName.replace(/[^a-z0-9]/g, '_')}`;
      config += `    default_backend ${backendName}\n`;
    }
    config += `\n`;
  }

  // MySQL frontend
  if (mysqlBackends.length > 0) {
    config += `# MySQL Databases (port 3306)\n`;
    config += `frontend mysql_frontend\n`;
    config += `    bind *:3306\n`;
    config += `    mode tcp\n`;
    config += `    tcp-request inspect-delay 5s\n`;
    config += `    tcp-request content accept if { req_ssl_hello_type 1 }\n`;

    for (const backend of mysqlBackends) {
      const backendName = `mysql_${backend.instanceName.replace(/[^a-z0-9]/g, '_')}`;
      config += `    use_backend ${backendName} if { req.ssl_sni -i ${backend.domain} }\n`;
    }

    if (mysqlBackends.length === 1) {
      const backend = mysqlBackends[0];
      const backendName = `mysql_${backend.instanceName.replace(/[^a-z0-9]/g, '_')}`;
      config += `    default_backend ${backendName}\n`;
    }
    config += `\n`;
  }

  // PostgreSQL backends
  for (const backend of postgresBackends) {
    const backendName = `postgres_${backend.instanceName.replace(/[^a-z0-9]/g, '_')}`;
    config += `# PostgreSQL: ${backend.instanceName} (${backend.domain})\n`;
    config += `backend ${backendName}\n`;
    config += `    mode tcp\n`;
    config += `    option tcp-check\n`;
    config += `    server ${backend.instanceName} 127.0.0.1:${backend.port} check\n`;
    config += `\n`;
  }

  // MySQL backends
  for (const backend of mysqlBackends) {
    const backendName = `mysql_${backend.instanceName.replace(/[^a-z0-9]/g, '_')}`;
    config += `# MySQL: ${backend.instanceName} (${backend.domain})\n`;
    config += `backend ${backendName}\n`;
    config += `    mode tcp\n`;
    config += `    option tcp-check\n`;
    config += `    server ${backend.instanceName} 127.0.0.1:${backend.port} check\n`;
    config += `\n`;
  }

  // Stats page
  config += `# Stats Page\n`;
  config += `listen stats\n`;
  config += `    bind *:8404\n`;
  config += `    mode http\n`;
  config += `    stats enable\n`;
  config += `    stats uri /stats\n`;
  config += `    stats refresh 10s\n`;
  config += `    stats admin if TRUE\n`;

  return config;
}

// Main execution
try {
  console.log('Loading HAProxy backends...');
  const backends = loadBackends();
  
  if (Object.keys(backends).length === 0) {
    console.log('No backends found. Exiting.');
    process.exit(0);
  }

  console.log(`Found ${Object.keys(backends).length} backend(s)`);

  // Separate by type
  const postgresBackends = [];
  const mysqlBackends = [];
  
  for (const backend of Object.values(backends)) {
    if (backend.dbType === 'postgres') {
      postgresBackends.push(backend);
    } else {
      mysqlBackends.push(backend);
    }
  }

  console.log(`Generating config: ${postgresBackends.length} PostgreSQL, ${mysqlBackends.length} MySQL`);

  // Generate config
  const config = generateConfig(postgresBackends, mysqlBackends);

  // Write locally first
  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
  }
  fs.writeFileSync(HAPROXY_CONFIG, config, { mode: 0o644 });
  console.log(`Config written to ${HAPROXY_CONFIG}`);

  // Copy to system location
  try {
    execSync(`sudo mkdir -p /etc/haproxy`, { stdio: 'pipe' });
    execSync(`sudo cp ${HAPROXY_CONFIG} ${HAPROXY_SYSTEM_CONFIG}`, { stdio: 'pipe' });
    execSync(`sudo chown haproxy:haproxy ${HAPROXY_SYSTEM_CONFIG}`, { stdio: 'pipe' });
    execSync(`sudo chmod 644 ${HAPROXY_SYSTEM_CONFIG}`, { stdio: 'pipe' });
    console.log(`Config copied to ${HAPROXY_SYSTEM_CONFIG}`);

    // Validate config
    console.log('Validating HAProxy config...');
    execSync(`sudo haproxy -c -f ${HAPROXY_SYSTEM_CONFIG}`, { stdio: 'inherit' });

    // Reload HAProxy
    console.log('Reloading HAProxy...');
    try {
      execSync('sudo systemctl reload haproxy', { stdio: 'inherit' });
      console.log('✅ HAProxy reloaded successfully!');
    } catch (error) {
      console.log('Reload failed, attempting restart...');
      execSync('sudo systemctl restart haproxy', { stdio: 'inherit' });
      console.log('✅ HAProxy restarted successfully!');
    }
  } catch (error) {
    console.error('❌ Failed to deploy config:', error.message);
    process.exit(1);
  }

  console.log('\n✅ HAProxy configuration regenerated successfully!');
} catch (error) {
  console.error('❌ Error:', error.message);
  process.exit(1);
}

